name: Auto Update Rules

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run convert scripts
        run: |
          python scripts/convert_porn.py
          python scripts/convert_ai.py

      - name: Commit & Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add rules/
          git diff-index --quiet HEAD || git commit -m "Auto update QX rules"
          git push
